// Mocks generated by Mockito 5.4.4 from annotations
// in food/test/file.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:food/main.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Car].
///
/// See the documentation for Mockito's code generation for more information.
class MockCar extends _i1.Mock implements _i2.Car {
  MockCar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  set name(String? _name) => super.noSuchMethod(
        Invocation.setter(
          #name,
          _name,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get price => (super.noSuchMethod(
        Invocation.getter(#price),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#price),
        ),
      ) as String);

  @override
  set price(String? _price) => super.noSuchMethod(
        Invocation.setter(
          #price,
          _price,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get distance => (super.noSuchMethod(
        Invocation.getter(#distance),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#distance),
        ),
      ) as String);

  @override
  set distance(String? _distance) => super.noSuchMethod(
        Invocation.setter(
          #distance,
          _distance,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get image => (super.noSuchMethod(
        Invocation.getter(#image),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#image),
        ),
      ) as String);

  @override
  set image(String? _image) => super.noSuchMethod(
        Invocation.setter(
          #image,
          _image,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
